//
//  CustomDataReceiverInteractor.swift
//  Demo
//
//  Created by Ahmed Henawey on 6/11/18.
//  Copyright (c) 2018 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomDataReceiverBusinessLogic
{
  func doSomething(request: CustomDataReceiver.Something.Request)
}

protocol CustomDataReceiverDataStore
{
  //var name: String { get set }
}

class CustomDataReceiverInteractor: CustomDataReceiverBusinessLogic, CustomDataReceiverDataStore
{
  var presenter: CustomDataReceiverPresentationLogic?
  var worker: CustomDataReceiverWorker?
  
  // MARK: Do something
  
  func doSomething(request: CustomDataReceiver.Something.Request)
  {
    
    worker = CustomDataReceiverWorker()
    worker?.doSomeWork()
    
    let response = CustomDataReceiver.Something.Response(receivedData: selectedItemTitle)
    presenter?.presentSomething(response: response)
  }
}
