//
//  CustomDataReceiverPresenter.swift
//  Demo
//
//  Created by Ahmed Henawey on 6/11/18.
//  Copyright (c) 2018 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomDataReceiverPresentationLogic
{
  func presentSomething(response: CustomDataReceiver.Something.Response)
}

class CustomDataReceiverPresenter: CustomDataReceiverPresentationLogic
{
  weak var viewController: CustomDataReceiverDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CustomDataReceiver.Something.Response)
  {
    let viewModel = CustomDataReceiver.Something.ViewModel(receivedData: response.receivedData)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
