//
//  CustomDataReceiverWorker.swift
//  Demo
//
//  Created by Ahmed Henawey on 6/11/18.
//  Copyright (c) 2018 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CustomDataReceiverWorker
{
  func doSomeWork()
  {
  }
}
