//
//  CustomDataReceiverRouter.swift
//  Demo
//
//  Created by Ahmed Henawey on 6/11/18.
//  Copyright (c) 2018 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CustomDataReceiverRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CustomDataReceiverDataPassing
{
  var dataStore: CustomDataReceiverDataStore? { get }
}

class CustomDataReceiverRouter: NSObject, CustomDataReceiverRoutingLogic, CustomDataReceiverDataPassing
{
  weak var viewController: CustomDataReceiverViewController?
  var dataStore: CustomDataReceiverDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CustomDataReceiverViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CustomDataReceiverDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
