//
//  CustomDataReceiverViewController.swift
//  Demo
//
//  Created by Ahmed Henawey on 6/11/18.
//  Copyright (c) 2018 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomDataReceiverDisplayLogic: class
{
  func displaySomething(viewModel: CustomDataReceiver.Something.ViewModel)
}

class CustomDataReceiverViewController: UIViewController, CustomDataReceiverDisplayLogic
{
  var interactor: CustomDataReceiverBusinessLogic?
  var router: (NSObjectProtocol & CustomDataReceiverRoutingLogic & CustomDataReceiverDataPassing)?

  // MARK: Object lifecycle
  
    @IBOutlet weak var receivedDataLabel: UILabel!
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CustomDataReceiverInteractor()
    let presenter = CustomDataReceiverPresenter()
    let router = CustomDataReceiverRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = CustomDataReceiver.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CustomDataReceiver.Something.ViewModel)
  {
    receivedDataLabel.text = viewModel.receivedData
  }
}
